### ISSUE TITLE
Feature request: don't use modal window for the run

### ISSUE THREAD

**Issue by marnen** [LeviBotelho/LearnAngular#33]
I found that sometimes I wanted to build the code bit by bit, and then run each bit to see what it did. But the modal window made that less convenient than a non-modal interface like that of jsFiddle or Codepen.

**Comment by LeviBotelho** [comment]
I agree with you regarding this particular use case, and actually hesitated quite a bit when first designing the UI. However I settled on the modal design because it allows those on smaller screens to use the site more comfortably. I do most of my work on a 27" and could easily take another window in the UI for results, but it's already cramped on a 14" notebook screen and I feel that another window would be too much. jsFiddle + Codepen have an advantage over this site in that they don't need to display a large reading pane in addition to the code :).

That said if you have a particular design in mind and want to implement it and do a pull request I'd be happy to take a look. If it makes things easier without impacting usability (the current site is usable even on a mobile phone - not that you'd want to, but still) then I'd be happy to integrate it!
