### ISSUE TITLE
Syntax error in instructions

### ISSUE THREAD

**Issue by GixxedSpyder** [LeviBotelho/LearnAngular#34]
In your instructions you show them the proper code to write the first module:
angular.module("root",[])

this is incorrect, it should be with single quotes:
angular.module('root',[])

**Comment by LeviBotelho** [comment]
Both ways are correct. Javascript allows strings to be represented using single or double quotes. I use double quotes because it allows me to use single quotes in the string without escaping.

**Comment by GixxedSpyder** [comment]
Cool, your compiler said it was incorrect - might want to fix that.

**Comment by LeviBotelho** [comment]
My compiler???

Care to provide a screenshot?

**Comment by GixxedSpyder** [comment]
It's working now, previously if there were double quotes around root - when you ran the program it printed {{message}} instead of Hello World.  When I hit the I'm stuck button, it switched my double quotes around root to single quotes (everything else remained as double quotes) and it worked.  Thanks!

**Comment by LeviBotelho** [comment]
The "switch" is simply because each lesson has a predefined answer. In the predefined answer I must have used single quotes instead of double which I normally use. The fact that you were seeing {{message}} would have been because there was an error somewhere else in your code. Anyways, glad it's working :smile:.
