### ISSUE TITLE
Consider using single quotes ' in JavaScript instead of double quotes "

### ISSUE THREAD

**Issue by erikeckhardt** [levibotelho/LearnAngular#45]
Consider using single quotes consistently in JavaScript, because this makes it much easier, as a matter of habit, to include Html that uses double quotes. I understand that in general, especially when using something like angular that is in essence a templating mechanism, that we would usually not put html in strings in JavaScript. However, it does occur at times (and consider jQuery selectors such as `$('div[data-flag="true"]')`.

I honestly don't know if this recommendation is truly a global one in the community, but I for one find JavaScript single quotes easier on the eyes, and enjoy the difference from the more "bulky" double quotes that are used in HTML.

**Comment by steveambielli** [comment]
I thought the same thing and would prefer single quotes. When going through the tutorial I was using single quotes instead.

**Comment by levibotelho** [comment]
@erikeckhardt In regards to all of your comments/issues, I really appreciate the time and effort you put into creating them. It's great to see that there's community engagement around the site and that there are people out there who want to help make it better.

I'm going to close this issue because it brings little to no benefit to the end user while having a number of drawbacks:

- It reflects a coding style. Single quotes are indeed popular, but it's a tabs vs. spaces argument when you boil it all down.
- Some people prefer double quotes and we could have just as easily gotten a "move to double quotes" issue had we written this with single quotes.
- It risks creating bugs in the lessons.
- We would need to change the quote style in the application as well in order to remain consistent, which would risk creating bugs there as well.
- Users are free to go with single quotes when they write their test code. If this isn't the case then this specific detail needs its own issue. Users should be free to use any legal coding style when going through the lessons.
- There are work items in the queue (like your #43) that need work but benefit the user much more. This is especially important as I'm currently busy with other projects. Should anybody be able to spend a bit of time and want to contribute to make the site better, I'd rather them pick up a work item that improves the application in a more meaningful way.
