### ISSUE TITLE
Run not showing results

### ISSUE THREAD

**Issue by chemturion** [levibotelho/LearnAngular#50]
I'm not able to see if my code works after clicking `Run`, and even after doing the `I'm Stuck!` thing. The popup window shows no output whatsoever.

![learn-angular-org-issue](https://cloud.githubusercontent.com/assets/6170077/14621025/9dd7302e-0585-11e6-91ad-d8fa18d7f9f3.png)

**Comment by levibotelho** [comment]
What does the JavaScript console say?

**Comment by chemturion** [comment]
Quick note: it does work on iPhone Chrome browser, latest updates.

```2angular.min.js:85 Error: Blocked a frame with origin "http://www.learn-angular.org" from accessing a cross-origin frame.
    at Error (native)
    at h.n.run (http://www.learn-angular.org/bundles/scripts?v=r88Q425Dp0R03EpeDj-uTsZ6EkZzuvATUk6abF9Wcks1:1:1776)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:163:57
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:179:344
    at h.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:102:456)
    at h.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:103:212)
    at HTMLButtonElement.<anonymous> (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:179:326)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:27:208
    at q (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:7:386)
    at HTMLButtonElement.Yc.c (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js:27:190)(anonymous function) @ angular.min.js:85```

![image](https://cloud.githubusercontent.com/assets/6170077/14647052/95d96c24-0621-11e6-966c-77a97084733c.png)

**Comment by levibotelho** [comment]
It shouldn't be browser dependent -- the issue is that the frame is from a different origin than the site. This error USED to happen because people would land on learn-angular.org and access an AJAX endpoint in the last lesson from www.learn-angular.org. I fixed that by modifying the DNS record.

I honestly can't see why this error would occur because the frame is on the *same* site. It's not even loading anything -- the site just writes to the frame as you can see [here](https://github.com/levibotelho/LearnAngular/blob/master/AngularTutorial.Web/Scripts/Controllers.js#L63). It's as same-origin as same-origin can be.

I'm also finding this difficult to comprehend because you're the first person to report this, and with the amount of traffic the site gets someone else certainly should have reported it by now. I for one cannot reproduce (tested on Chrome on Windows and Chromium on Ubuntu).

Do you have access to a Windows machine by any chance? I'm wondering if this is specific to the Mac version of Chrome. Maybe I'm way off base here but I really have no idea... Might need some help from Stack Overflow.

**Comment by chemturion** [comment]
Probably a Chrome on Mac issue. No problems in Safari. Thanks for checking into the issue.
