### ISSUE TITLE
The Value Recipe needs some update

### ISSUE THREAD

**Issue by prav712** [levibotelho/LearnAngular#52]
In Example section:

Below line needs to be added otherwise it throws an exception:
Reference your "Services" module in the HTML page.

Thanks,
Praveen

**Comment by levibotelho** [comment]
>Time to write the controller. Declare a new controller on the root module. Inject the multiplier service as well as the $scope. Don't forget to inject services into the module declaration!

Does that not cover it?

**Comment by prav712** [comment]
Very much 👍

**Comment by prav712** [comment]
Not very much actually.
Injection wont work until we reference related module to the corresponding HTML.

**Comment by levibotelho** [comment]
You mean you write your service module in a .js file and that you need to add a `<script>` tag to reference that .js file? Is that what you're saying is missing?

**Comment by prav712** [comment]
Yes sir :)

**Comment by levibotelho** [comment]
Okay, I see. I'm not going to add this to the lesson because it's basic web development knowledge that you need to reference JS files that you want to execute. The site is targeted to folks who already know the basics of web development and want to learn Angular JS, so it's assumed that the user would know this already.
